### ISSUE TITLE
Set gh-pages as the primary branch

### ISSUE THREAD

**Issue by benbalter** [CMSgov/HealthCare.gov-Styleguide#166]
The repository's default branch (meaning the branch pull requests are submitted against and the first one viewed when visiting via the web interface) is set as `master`, but it appears the primary branch is the `gh-pages` branch, with the history of the two [diverging](https://github.com/CMSgov/HealthCare.gov-Styleguide/compare/gh-pages...master).

You can [set the default branch as `gh-pages`](https://help.github.com/articles/setting-the-default-branch/) to ensure visitors to the repository via the GitHub link see the live version of the site with the latest code, rather that requiring the extra step of needing to know to swithc branches. 

Best practices would dictate that you also delete the `master` branch, if it's not part of your workflow, to avoid confusion, both internally and when engaging external developers.

**Comment by mliupaeter** [comment]
Thank you Ben for the suggestion and input.  We understand what you are saying and recommending here.  The thought behind our setup of our master and gh-pages branching strategy was to follow the  have:
* “master branch” – contain content/code which developers could download directly and incorporate the files right away in their own healthcare.gov projects
* “gh-pages branch” – contain the http://styleguide.healthcare.gov website code and content
 
It appears as though the twitter bootstrap repo follows a similar model with their master and gh-pages branches (https://github.com/twbs/bootstrap).  We've updated our strategy in our [readme] (https://github.com/CMSgov/HealthCare.gov-Styleguide/blob/master/README.md) and [contribute] (https://github.com/CMSgov/HealthCare.gov-Styleguide/blob/master/CONTRIBUTING.md) files to explain our line of thinking on the branches.

**Comment by benbalter** [comment]
That makes sense. Thanks for clarifying, and @shredtechular's changes over in https://github.com/CMSgov/HealthCare.gov-Styleguide/commit/51e966390cb9701ab128f99bec9d0e119287134b goes a long way to help.

I guess my biggest point of confusion is that the project is called a "style guide", something I'd traditionally associate with a document (hence thinking `gh-pages` should be the primary branch), but it appears to be a common CSS framework (the `master` branch), with associated documentation. 

To note, it also looks like there's a `DEV` branch, which [diverges slightly from `gh-pages](https://github.com/CMSgov/HealthCare.gov-Styleguide/compare/DEV...gh-pages).

**Comment by mliupaeter** [comment]
That makes sense Ben. We appreciate the feedback and suggestion on adding additional details around the differences between the gh-pages and master branches. You are absolutely correct that it is a common CSS framework with assets that can be utilized by other developers. 

Our intention was to provide those assets along with a website that could also be quickly referenced with live examples to see as well. We will continue to ensure the site is updated appropriately and attempt to make the instructions as clear as possible. Please let us know if you have any other suggestions, but for now, we think this issue is resolved and closing it out. Thanks again!
